FROM debian:11

# https://github.com/actions/runner-images/issues/6930
ARG UID=1000

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update \
    && apt-get install -y --without-recommends python3 python3-pip python3-venv \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* \
    && useradd -m -u ${UID} github

USER ${UID}

RUN python3 -m pip --no-cache-dir install --user pipx \
    && python3 -m pipx install ansible --include-deps --pip-args="--no-cache-dir"
