FROM fedora:38

# https://github.com/actions/runner-images/issues/6930
ARG UID=1000

RUN dnf install -y python3 python3-pip \
    && dnf clean all \
    && useradd -m -u ${UID} github

USER ${UID}

RUN python3 -m pip --no-cache-dir install --user pipx \
    && python3 -m pipx ensurepath \
    && python3 -m pipx install ansible --include-deps --pip-args="--no-cache-dir"
